# Generated by Django 2.2.2 on 2019-10-23 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airline',
            fields=[
                ('airline_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('head_quarter_city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='flight',
            fields=[
                ('flight_number', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('arrival_time', models.TimeField(blank=True)),
                ('departure_time', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('reviews', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='hotel_class',
            fields=[
                ('flight_number', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('accomadation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tour',
            fields=[
                ('tour_id', models.AutoField(primary_key=True, serialize=False)),
                ('tour_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('fare', models.IntegerField()),
                ('reviews', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True)),
            ],
            options={
                'unique_together': {('user_id', 'email')},
            },
        ),
        migrations.CreateModel(
            name='room_type',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'unique_together': {('room_number', 'room_id')},
            },
        ),
        migrations.CreateModel(
            name='has_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravellingMamas.rooms')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravellingMamas.room_type')),
            ],
            options={
                'unique_together': {('room_id', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='has_flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravellingMamas.flight')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravellingMamas.hotel_class')),
            ],
            options={
                'unique_together': {('flight_number', 'type')},
            },
        ),
        migrations.CreateModel(
            name='consists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravellingMamas.hotel')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravellingMamas.room_type')),
            ],
            options={
                'unique_together': {('hotel_id', 'room_id')},
            },
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravellingMamas.flight')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravellingMamas.hotel')),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravellingMamas.tour')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravellingMamas.user')),
            ],
            options={
                'unique_together': {('user_id', 'flight_number', 'hotel_id', 'tour_id')},
            },
        ),
        migrations.CreateModel(
            name='belong_to',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravellingMamas.airline')),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravellingMamas.flight')),
            ],
            options={
                'unique_together': {('airline_id', 'flight_number')},
            },
        ),
    ]
