# Generated by Django 2.2 on 2019-10-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravellingMamas', '0004_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='check_in',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='check_out',
            field=models.CharField(max_length=100),
        ),
    ]
