# Generated by Django 2.2 on 2019-10-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravellingMamas', '0005_auto_20191026_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='mobile_number',
            field=models.CharField(max_length=100),
        ),
    ]
