# Generated by Django 2.2 on 2019-10-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravellingMamas', '0008_flight_prime'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_prime',
            name='date',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
